name: Waiting for checks and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: # This name is the one to be used in `running-workflow-name`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'deploy' # HERE

      - uses: actions/checkout@master
      - name: Deploy to staging
        env:
            VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        uses: teamnovu/vapor-action@master
        with:
            args: deploy staging